# Generated by Django 5.2.1 on 2025-05-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("fire", "Fire"),
                    ("accident", "Accident"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
