# Generated by Django 5.2.1 on 2025-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0002_incident_incident_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
